# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import scheduler_pb2 as scheduler__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in scheduler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddSchedule = channel.unary_unary(
                '/runtimePackage.Scheduler/AddSchedule',
                request_serializer=scheduler__pb2.AddScheduleRequest.SerializeToString,
                response_deserializer=scheduler__pb2.AddScheduleResponse.FromString,
                _registered_method=True)
        self.LoadSchedules = channel.unary_unary(
                '/runtimePackage.Scheduler/LoadSchedules',
                request_serializer=scheduler__pb2.LoadSchedulesRequest.SerializeToString,
                response_deserializer=scheduler__pb2.LoadSchedulesResponse.FromString,
                _registered_method=True)
        self.GetWebsiteSchedules = channel.unary_unary(
                '/runtimePackage.Scheduler/GetWebsiteSchedules',
                request_serializer=scheduler__pb2.GetWebsiteSchedulesRequest.SerializeToString,
                response_deserializer=scheduler__pb2.GetWebsiteSchedulesResponse.FromString,
                _registered_method=True)
        self.DeleteWebsiteSchedule = channel.unary_unary(
                '/runtimePackage.Scheduler/DeleteWebsiteSchedule',
                request_serializer=scheduler__pb2.DeleteWebsiteScheduleRequest.SerializeToString,
                response_deserializer=scheduler__pb2.DeleteWebsiteScheduleResponse.FromString,
                _registered_method=True)
        self.GetSchedule = channel.unary_unary(
                '/runtimePackage.Scheduler/GetSchedule',
                request_serializer=scheduler__pb2.GetScheduleRequest.SerializeToString,
                response_deserializer=scheduler__pb2.GetScheduleResponse.FromString,
                _registered_method=True)


class SchedulerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWebsiteSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWebsiteSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSchedule,
                    request_deserializer=scheduler__pb2.AddScheduleRequest.FromString,
                    response_serializer=scheduler__pb2.AddScheduleResponse.SerializeToString,
            ),
            'LoadSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadSchedules,
                    request_deserializer=scheduler__pb2.LoadSchedulesRequest.FromString,
                    response_serializer=scheduler__pb2.LoadSchedulesResponse.SerializeToString,
            ),
            'GetWebsiteSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWebsiteSchedules,
                    request_deserializer=scheduler__pb2.GetWebsiteSchedulesRequest.FromString,
                    response_serializer=scheduler__pb2.GetWebsiteSchedulesResponse.SerializeToString,
            ),
            'DeleteWebsiteSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWebsiteSchedule,
                    request_deserializer=scheduler__pb2.DeleteWebsiteScheduleRequest.FromString,
                    response_serializer=scheduler__pb2.DeleteWebsiteScheduleResponse.SerializeToString,
            ),
            'GetSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchedule,
                    request_deserializer=scheduler__pb2.GetScheduleRequest.FromString,
                    response_serializer=scheduler__pb2.GetScheduleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runtimePackage.Scheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('runtimePackage.Scheduler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Scheduler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Scheduler/AddSchedule',
            scheduler__pb2.AddScheduleRequest.SerializeToString,
            scheduler__pb2.AddScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Scheduler/LoadSchedules',
            scheduler__pb2.LoadSchedulesRequest.SerializeToString,
            scheduler__pb2.LoadSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWebsiteSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Scheduler/GetWebsiteSchedules',
            scheduler__pb2.GetWebsiteSchedulesRequest.SerializeToString,
            scheduler__pb2.GetWebsiteSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWebsiteSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Scheduler/DeleteWebsiteSchedule',
            scheduler__pb2.DeleteWebsiteScheduleRequest.SerializeToString,
            scheduler__pb2.DeleteWebsiteScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Scheduler/GetSchedule',
            scheduler__pb2.GetScheduleRequest.SerializeToString,
            scheduler__pb2.GetScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
