// source: evaluations.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.runtimePackage.AddEvaluationRequest', null, global);
goog.exportSymbol('proto.runtimePackage.AddEvaluationResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.runtimePackage.AddEvaluationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.runtimePackage.AddEvaluationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.runtimePackage.AddEvaluationRequest.displayName = 'proto.runtimePackage.AddEvaluationRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.runtimePackage.AddEvaluationResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.runtimePackage.AddEvaluationResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.runtimePackage.AddEvaluationResponse.displayName = 'proto.runtimePackage.AddEvaluationResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.runtimePackage.AddEvaluationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.runtimePackage.AddEvaluationRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.runtimePackage.AddEvaluationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
qualwebVersion: jspb.Message.getFieldWithDefault(msg, 1, ""),
inputUrl: jspb.Message.getFieldWithDefault(msg, 2, ""),
domainName: jspb.Message.getFieldWithDefault(msg, 3, ""),
domain: jspb.Message.getFieldWithDefault(msg, 4, ""),
uri: jspb.Message.getFieldWithDefault(msg, 5, ""),
completeUrl: jspb.Message.getFieldWithDefault(msg, 6, ""),
mobile: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
landscape: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
displayWidth: jspb.Message.getFieldWithDefault(msg, 9, 0),
displayHeight: jspb.Message.getFieldWithDefault(msg, 10, 0),
dom: jspb.Message.getFieldWithDefault(msg, 11, ""),
title: jspb.Message.getFieldWithDefault(msg, 12, ""),
elementCount: jspb.Message.getFieldWithDefault(msg, 13, 0),
passed: jspb.Message.getFieldWithDefault(msg, 14, 0),
warning: jspb.Message.getFieldWithDefault(msg, 15, 0),
failed: jspb.Message.getFieldWithDefault(msg, 16, 0),
inapplicable: jspb.Message.getFieldWithDefault(msg, 17, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.runtimePackage.AddEvaluationRequest}
 */
proto.runtimePackage.AddEvaluationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.runtimePackage.AddEvaluationRequest;
  return proto.runtimePackage.AddEvaluationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.runtimePackage.AddEvaluationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.runtimePackage.AddEvaluationRequest}
 */
proto.runtimePackage.AddEvaluationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setQualwebVersion(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setInputUrl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDomainName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDomain(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUri(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCompleteUrl(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMobile(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLandscape(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDisplayWidth(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDisplayHeight(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setDom(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setElementCount(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPassed(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWarning(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFailed(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInapplicable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.runtimePackage.AddEvaluationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.runtimePackage.AddEvaluationRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.runtimePackage.AddEvaluationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQualwebVersion();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInputUrl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDomainName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDomain();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getUri();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCompleteUrl();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getMobile();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getLandscape();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getDisplayWidth();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getDisplayHeight();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getDom();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getElementCount();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getPassed();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getWarning();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
  f = message.getFailed();
  if (f !== 0) {
    writer.writeInt32(
      16,
      f
    );
  }
  f = message.getInapplicable();
  if (f !== 0) {
    writer.writeInt32(
      17,
      f
    );
  }
};


/**
 * optional string qualweb_version = 1;
 * @return {string}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getQualwebVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setQualwebVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string input_url = 2;
 * @return {string}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getInputUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setInputUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string domain_name = 3;
 * @return {string}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getDomainName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setDomainName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string domain = 4;
 * @return {string}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getDomain = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setDomain = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string uri = 5;
 * @return {string}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setUri = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string complete_url = 6;
 * @return {string}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getCompleteUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setCompleteUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional bool mobile = 7;
 * @return {boolean}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getMobile = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setMobile = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool landscape = 8;
 * @return {boolean}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getLandscape = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setLandscape = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional int32 display_width = 9;
 * @return {number}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getDisplayWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setDisplayWidth = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 display_height = 10;
 * @return {number}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getDisplayHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setDisplayHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional string dom = 11;
 * @return {string}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getDom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setDom = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string title = 12;
 * @return {string}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional int32 element_count = 13;
 * @return {number}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getElementCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setElementCount = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional int32 passed = 14;
 * @return {number}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getPassed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setPassed = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional int32 warning = 15;
 * @return {number}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getWarning = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setWarning = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


/**
 * optional int32 failed = 16;
 * @return {number}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getFailed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setFailed = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional int32 inapplicable = 17;
 * @return {number}
 */
proto.runtimePackage.AddEvaluationRequest.prototype.getInapplicable = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {number} value
 * @return {!proto.runtimePackage.AddEvaluationRequest} returns this
 */
proto.runtimePackage.AddEvaluationRequest.prototype.setInapplicable = function(value) {
  return jspb.Message.setProto3IntField(this, 17, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.runtimePackage.AddEvaluationResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.runtimePackage.AddEvaluationResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.runtimePackage.AddEvaluationResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.runtimePackage.AddEvaluationResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
statusCode: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.runtimePackage.AddEvaluationResponse}
 */
proto.runtimePackage.AddEvaluationResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.runtimePackage.AddEvaluationResponse;
  return proto.runtimePackage.AddEvaluationResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.runtimePackage.AddEvaluationResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.runtimePackage.AddEvaluationResponse}
 */
proto.runtimePackage.AddEvaluationResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStatusCode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.runtimePackage.AddEvaluationResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.runtimePackage.AddEvaluationResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.runtimePackage.AddEvaluationResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.runtimePackage.AddEvaluationResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatusCode();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 status_code = 1;
 * @return {number}
 */
proto.runtimePackage.AddEvaluationResponse.prototype.getStatusCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.runtimePackage.AddEvaluationResponse} returns this
 */
proto.runtimePackage.AddEvaluationResponse.prototype.setStatusCode = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


goog.object.extend(exports, proto.runtimePackage);
