apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: evaluations-database-autoscaler
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: evaluations-database
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: issues-database-autoscaler
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: issues-database
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: evaluations-autoscaler
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: evaluations
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: issues-autoscaler
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: issues
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
---