syntax = "proto3";

package runtimePackage;

message AddScheduleRequest {
    int32 monitoring_id = 1;
    repeated int32 webpages_ids = 2;
    string schedule_type = 3;
    int32 day = 4;
    int32 month = 5;
    int32 year = 6;
    int32 hour = 7;
    int32 minute = 8;
    int32 second = 9;
    int32 day_of_week = 10;
}

message AddScheduleResponse {
    int32 status_code = 1;
    int32 schedule_id = 2;
}

message LoadSchedulesRequest {
}

message Schedule {
    int32 id = 1;
    int32 monitoring_id = 2;
    repeated int32 webpages_ids = 3;
    string schedule_type = 4;
    int32 day = 5;
    int32 month = 6;
    int32 year = 7;
    int32 hour = 8;
    int32 minute = 9;
    int32 second = 10;
    int32 day_of_week = 11;
}

message LoadSchedulesResponse {
    int32 status_code = 1;
    repeated Schedule schedules = 2;
}

message GetWebsiteSchedulesRequest {
    int32 monitoring_id = 1;
}

message GetWebsiteSchedulesResponse {
    int32 status_code = 1;
    repeated int32 schedules_ids = 2;
}

message DeleteWebsiteScheduleRequest {
    int32 schedule_id = 1;
}

message DeleteWebsiteScheduleResponse {
    int32 status_code = 1;
    int32 schedule_id = 2;
}

message GetScheduleRequest {
    int32 schedule_id = 1;
}

message GetScheduleResponse {
    int32 status_code = 1;
    Schedule schedule = 2;
}

service Scheduler {
    rpc AddSchedule (AddScheduleRequest) returns (AddScheduleResponse);
    rpc LoadSchedules (LoadSchedulesRequest) returns (LoadSchedulesResponse);
    rpc GetWebsiteSchedules (GetWebsiteSchedulesRequest) returns (GetWebsiteSchedulesResponse);
    rpc DeleteWebsiteSchedule (DeleteWebsiteScheduleRequest) returns (DeleteWebsiteScheduleResponse);
    rpc GetSchedule (GetScheduleRequest) returns (GetScheduleResponse);
}