# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x0eruntimePackage\"T\n\x0e\x41\x64\x64UserRequest\x12\x10\n\x08\x61uth0_id\x18\x01 \x01(\t\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x0f\n\x07picture\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"7\n\x0f\x41\x64\x64UserResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"\"\n\x0eGetUserRequest\x12\x10\n\x08\x61uth0_id\x18\x01 \x01(\t\"i\n\x0fGetUserResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x10\n\x08nickname\x18\x03 \x01(\t\x12\x0f\n\x07picture\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t2\x9f\x01\n\x05Users\x12J\n\x07\x41\x64\x64User\x12\x1e.runtimePackage.AddUserRequest\x1a\x1f.runtimePackage.AddUserResponse\x12J\n\x07GetUser\x12\x1e.runtimePackage.GetUserRequest\x1a\x1f.runtimePackage.GetUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDUSERREQUEST']._serialized_start=31
  _globals['_ADDUSERREQUEST']._serialized_end=115
  _globals['_ADDUSERRESPONSE']._serialized_start=117
  _globals['_ADDUSERRESPONSE']._serialized_end=172
  _globals['_GETUSERREQUEST']._serialized_start=174
  _globals['_GETUSERREQUEST']._serialized_end=208
  _globals['_GETUSERRESPONSE']._serialized_start=210
  _globals['_GETUSERRESPONSE']._serialized_end=315
  _globals['_USERS']._serialized_start=318
  _globals['_USERS']._serialized_end=477
# @@protoc_insertion_point(module_scope)
