# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import evaluations_pb2 as evaluations__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in evaluations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EvaluationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddMonitoringRegistry = channel.unary_unary(
                '/runtimePackage.Evaluations/AddMonitoringRegistry',
                request_serializer=evaluations__pb2.AddMonitoringRegistryRequest.SerializeToString,
                response_deserializer=evaluations__pb2.AddMonitoringRegistryResponse.FromString,
                _registered_method=True)
        self.AddEvaluation = channel.unary_unary(
                '/runtimePackage.Evaluations/AddEvaluation',
                request_serializer=evaluations__pb2.AddEvaluationRequest.SerializeToString,
                response_deserializer=evaluations__pb2.AddEvaluationResponse.FromString,
                _registered_method=True)
        self.SetAccessibilityMetric = channel.unary_unary(
                '/runtimePackage.Evaluations/SetAccessibilityMetric',
                request_serializer=evaluations__pb2.SetAccessibilityMetricRequest.SerializeToString,
                response_deserializer=evaluations__pb2.SetAccessibilityMetricResponse.FromString,
                _registered_method=True)
        self.CalculateAccessibilityScore = channel.unary_unary(
                '/runtimePackage.Evaluations/CalculateAccessibilityScore',
                request_serializer=evaluations__pb2.CalculateAccessibilityScoreRequest.SerializeToString,
                response_deserializer=evaluations__pb2.CalculateAccessibilityScoreResponse.FromString,
                _registered_method=True)
        self.SetLatestEvaluation = channel.unary_unary(
                '/runtimePackage.Evaluations/SetLatestEvaluation',
                request_serializer=evaluations__pb2.SetLatestEvaluationRequest.SerializeToString,
                response_deserializer=evaluations__pb2.SetLatestEvaluationResponse.FromString,
                _registered_method=True)
        self.AddWebpages = channel.unary_unary(
                '/runtimePackage.Evaluations/AddWebpages',
                request_serializer=evaluations__pb2.AddWebpagesRequest.SerializeToString,
                response_deserializer=evaluations__pb2.AddWebpagesResponse.FromString,
                _registered_method=True)
        self.SetAccessibilityMetricAllWebsites = channel.unary_unary(
                '/runtimePackage.Evaluations/SetAccessibilityMetricAllWebsites',
                request_serializer=evaluations__pb2.SetAccessibilityMetricAllWebsitesRequest.SerializeToString,
                response_deserializer=evaluations__pb2.SetAccessibilityMetricAllWebsitesResponse.FromString,
                _registered_method=True)
        self.GetCurrentWarnings = channel.unary_unary(
                '/runtimePackage.Evaluations/GetCurrentWarnings',
                request_serializer=evaluations__pb2.GetCurrentWarningsRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetCurrentWarningsResponse.FromString,
                _registered_method=True)
        self.GetWebsiteScore = channel.unary_unary(
                '/runtimePackage.Evaluations/GetWebsiteScore',
                request_serializer=evaluations__pb2.GetWebsiteScoreRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetWebsiteScoreResponse.FromString,
                _registered_method=True)
        self.GetIssuesStats = channel.unary_unary(
                '/runtimePackage.Evaluations/GetIssuesStats',
                request_serializer=evaluations__pb2.GetIssuesStatsRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetIssuesStatsResponse.FromString,
                _registered_method=True)
        self.GetWebpageScreenshot = channel.unary_unary(
                '/runtimePackage.Evaluations/GetWebpageScreenshot',
                request_serializer=evaluations__pb2.GetWebpageScreenshotRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetWebpageScreenshotResponse.FromString,
                _registered_method=True)
        self.GetLatestEvaluations = channel.unary_unary(
                '/runtimePackage.Evaluations/GetLatestEvaluations',
                request_serializer=evaluations__pb2.GetLatestEvaluationsRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetLatestEvaluationsResponse.FromString,
                _registered_method=True)
        self.GetLatestAssertions = channel.unary_unary(
                '/runtimePackage.Evaluations/GetLatestAssertions',
                request_serializer=evaluations__pb2.GetLatestAssertionsRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetLatestAssertionsResponse.FromString,
                _registered_method=True)
        self.GetAssertionResults = channel.unary_unary(
                '/runtimePackage.Evaluations/GetAssertionResults',
                request_serializer=evaluations__pb2.GetAssertionResultsRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetAssertionResultsResponse.FromString,
                _registered_method=True)
        self.GetResultElement = channel.unary_unary(
                '/runtimePackage.Evaluations/GetResultElement',
                request_serializer=evaluations__pb2.GetResultElementsRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetResultElementsResponse.FromString,
                _registered_method=True)
        self.GetEvaluationHistory = channel.unary_unary(
                '/runtimePackage.Evaluations/GetEvaluationHistory',
                request_serializer=evaluations__pb2.GetEvaluationHistoryRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetEvaluationHistoryResponse.FromString,
                _registered_method=True)
        self.GetUserMonitoringRegistries = channel.unary_unary(
                '/runtimePackage.Evaluations/GetUserMonitoringRegistries',
                request_serializer=evaluations__pb2.GetUserMonitoringRegistriesRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetUserMonitoringRegistriesResponse.FromString,
                _registered_method=True)
        self.GetWebsiteMonitoringCycles = channel.unary_unary(
                '/runtimePackage.Evaluations/GetWebsiteMonitoringCycles',
                request_serializer=evaluations__pb2.GetWebsiteMonitoringCyclesRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetWebsiteMonitoringCyclesResponse.FromString,
                _registered_method=True)
        self.SetNewMonitoringCycle = channel.unary_unary(
                '/runtimePackage.Evaluations/SetNewMonitoringCycle',
                request_serializer=evaluations__pb2.SetNewMonitoringCycleRequest.SerializeToString,
                response_deserializer=evaluations__pb2.SetNewMonitoringCycleResponse.FromString,
                _registered_method=True)
        self.GetMonitoredWebpages = channel.unary_unary(
                '/runtimePackage.Evaluations/GetMonitoredWebpages',
                request_serializer=evaluations__pb2.GetMonitoredWebpagesRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetMonitoredWebpagesResponse.FromString,
                _registered_method=True)
        self.GetEvaluationInfo = channel.unary_unary(
                '/runtimePackage.Evaluations/GetEvaluationInfo',
                request_serializer=evaluations__pb2.GetEvaluationInfoRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetEvaluationInfoResponse.FromString,
                _registered_method=True)
        self.DeleteWebpage = channel.unary_unary(
                '/runtimePackage.Evaluations/DeleteWebpage',
                request_serializer=evaluations__pb2.DeleteWebpageRequest.SerializeToString,
                response_deserializer=evaluations__pb2.DeleteWebpageResponse.FromString,
                _registered_method=True)
        self.AddLatestEvaluationsToMonitoringCycle = channel.unary_unary(
                '/runtimePackage.Evaluations/AddLatestEvaluationsToMonitoringCycle',
                request_serializer=evaluations__pb2.AddLatestEvaluationsToMonitoringCycleRequest.SerializeToString,
                response_deserializer=evaluations__pb2.AddLatestEvaluationsToMonitoringCycleResponse.FromString,
                _registered_method=True)
        self.GetMonitoringRegistry = channel.unary_unary(
                '/runtimePackage.Evaluations/GetMonitoringRegistry',
                request_serializer=evaluations__pb2.GetMonitoringRegistryRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetMonitoringRegistryResponse.FromString,
                _registered_method=True)
        self.GetMonitoringCycle = channel.unary_unary(
                '/runtimePackage.Evaluations/GetMonitoringCycle',
                request_serializer=evaluations__pb2.GetMonitoringCycleRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetMonitoringCycleResponse.FromString,
                _registered_method=True)
        self.GetWebpageComparisonData = channel.unary_unary(
                '/runtimePackage.Evaluations/GetWebpageComparisonData',
                request_serializer=evaluations__pb2.GetWebpageComparisonDataRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetWebpageComparisonDataResponse.FromString,
                _registered_method=True)
        self.GetFailedTestsStats = channel.unary_unary(
                '/runtimePackage.Evaluations/GetFailedTestsStats',
                request_serializer=evaluations__pb2.GetFailedTestsStatsRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetFailedTestsStatsResponse.FromString,
                _registered_method=True)
        self.GetIntermediateCycles = channel.unary_unary(
                '/runtimePackage.Evaluations/GetIntermediateCycles',
                request_serializer=evaluations__pb2.GetIntermediateCyclesRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetIntermediateCyclesResponse.FromString,
                _registered_method=True)


class EvaluationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddMonitoringRegistry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddEvaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAccessibilityMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateAccessibilityScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLatestEvaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddWebpages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAccessibilityMetricAllWebsites(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentWarnings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWebsiteScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIssuesStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWebpageScreenshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestEvaluations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestAssertions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssertionResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResultElement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvaluationHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserMonitoringRegistries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWebsiteMonitoringCycles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNewMonitoringCycle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMonitoredWebpages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvaluationInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWebpage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddLatestEvaluationsToMonitoringCycle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMonitoringRegistry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMonitoringCycle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWebpageComparisonData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFailedTestsStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIntermediateCycles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EvaluationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddMonitoringRegistry': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMonitoringRegistry,
                    request_deserializer=evaluations__pb2.AddMonitoringRegistryRequest.FromString,
                    response_serializer=evaluations__pb2.AddMonitoringRegistryResponse.SerializeToString,
            ),
            'AddEvaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEvaluation,
                    request_deserializer=evaluations__pb2.AddEvaluationRequest.FromString,
                    response_serializer=evaluations__pb2.AddEvaluationResponse.SerializeToString,
            ),
            'SetAccessibilityMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAccessibilityMetric,
                    request_deserializer=evaluations__pb2.SetAccessibilityMetricRequest.FromString,
                    response_serializer=evaluations__pb2.SetAccessibilityMetricResponse.SerializeToString,
            ),
            'CalculateAccessibilityScore': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateAccessibilityScore,
                    request_deserializer=evaluations__pb2.CalculateAccessibilityScoreRequest.FromString,
                    response_serializer=evaluations__pb2.CalculateAccessibilityScoreResponse.SerializeToString,
            ),
            'SetLatestEvaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLatestEvaluation,
                    request_deserializer=evaluations__pb2.SetLatestEvaluationRequest.FromString,
                    response_serializer=evaluations__pb2.SetLatestEvaluationResponse.SerializeToString,
            ),
            'AddWebpages': grpc.unary_unary_rpc_method_handler(
                    servicer.AddWebpages,
                    request_deserializer=evaluations__pb2.AddWebpagesRequest.FromString,
                    response_serializer=evaluations__pb2.AddWebpagesResponse.SerializeToString,
            ),
            'SetAccessibilityMetricAllWebsites': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAccessibilityMetricAllWebsites,
                    request_deserializer=evaluations__pb2.SetAccessibilityMetricAllWebsitesRequest.FromString,
                    response_serializer=evaluations__pb2.SetAccessibilityMetricAllWebsitesResponse.SerializeToString,
            ),
            'GetCurrentWarnings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentWarnings,
                    request_deserializer=evaluations__pb2.GetCurrentWarningsRequest.FromString,
                    response_serializer=evaluations__pb2.GetCurrentWarningsResponse.SerializeToString,
            ),
            'GetWebsiteScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWebsiteScore,
                    request_deserializer=evaluations__pb2.GetWebsiteScoreRequest.FromString,
                    response_serializer=evaluations__pb2.GetWebsiteScoreResponse.SerializeToString,
            ),
            'GetIssuesStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIssuesStats,
                    request_deserializer=evaluations__pb2.GetIssuesStatsRequest.FromString,
                    response_serializer=evaluations__pb2.GetIssuesStatsResponse.SerializeToString,
            ),
            'GetWebpageScreenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWebpageScreenshot,
                    request_deserializer=evaluations__pb2.GetWebpageScreenshotRequest.FromString,
                    response_serializer=evaluations__pb2.GetWebpageScreenshotResponse.SerializeToString,
            ),
            'GetLatestEvaluations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestEvaluations,
                    request_deserializer=evaluations__pb2.GetLatestEvaluationsRequest.FromString,
                    response_serializer=evaluations__pb2.GetLatestEvaluationsResponse.SerializeToString,
            ),
            'GetLatestAssertions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestAssertions,
                    request_deserializer=evaluations__pb2.GetLatestAssertionsRequest.FromString,
                    response_serializer=evaluations__pb2.GetLatestAssertionsResponse.SerializeToString,
            ),
            'GetAssertionResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssertionResults,
                    request_deserializer=evaluations__pb2.GetAssertionResultsRequest.FromString,
                    response_serializer=evaluations__pb2.GetAssertionResultsResponse.SerializeToString,
            ),
            'GetResultElement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResultElement,
                    request_deserializer=evaluations__pb2.GetResultElementsRequest.FromString,
                    response_serializer=evaluations__pb2.GetResultElementsResponse.SerializeToString,
            ),
            'GetEvaluationHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvaluationHistory,
                    request_deserializer=evaluations__pb2.GetEvaluationHistoryRequest.FromString,
                    response_serializer=evaluations__pb2.GetEvaluationHistoryResponse.SerializeToString,
            ),
            'GetUserMonitoringRegistries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserMonitoringRegistries,
                    request_deserializer=evaluations__pb2.GetUserMonitoringRegistriesRequest.FromString,
                    response_serializer=evaluations__pb2.GetUserMonitoringRegistriesResponse.SerializeToString,
            ),
            'GetWebsiteMonitoringCycles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWebsiteMonitoringCycles,
                    request_deserializer=evaluations__pb2.GetWebsiteMonitoringCyclesRequest.FromString,
                    response_serializer=evaluations__pb2.GetWebsiteMonitoringCyclesResponse.SerializeToString,
            ),
            'SetNewMonitoringCycle': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNewMonitoringCycle,
                    request_deserializer=evaluations__pb2.SetNewMonitoringCycleRequest.FromString,
                    response_serializer=evaluations__pb2.SetNewMonitoringCycleResponse.SerializeToString,
            ),
            'GetMonitoredWebpages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMonitoredWebpages,
                    request_deserializer=evaluations__pb2.GetMonitoredWebpagesRequest.FromString,
                    response_serializer=evaluations__pb2.GetMonitoredWebpagesResponse.SerializeToString,
            ),
            'GetEvaluationInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvaluationInfo,
                    request_deserializer=evaluations__pb2.GetEvaluationInfoRequest.FromString,
                    response_serializer=evaluations__pb2.GetEvaluationInfoResponse.SerializeToString,
            ),
            'DeleteWebpage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWebpage,
                    request_deserializer=evaluations__pb2.DeleteWebpageRequest.FromString,
                    response_serializer=evaluations__pb2.DeleteWebpageResponse.SerializeToString,
            ),
            'AddLatestEvaluationsToMonitoringCycle': grpc.unary_unary_rpc_method_handler(
                    servicer.AddLatestEvaluationsToMonitoringCycle,
                    request_deserializer=evaluations__pb2.AddLatestEvaluationsToMonitoringCycleRequest.FromString,
                    response_serializer=evaluations__pb2.AddLatestEvaluationsToMonitoringCycleResponse.SerializeToString,
            ),
            'GetMonitoringRegistry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMonitoringRegistry,
                    request_deserializer=evaluations__pb2.GetMonitoringRegistryRequest.FromString,
                    response_serializer=evaluations__pb2.GetMonitoringRegistryResponse.SerializeToString,
            ),
            'GetMonitoringCycle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMonitoringCycle,
                    request_deserializer=evaluations__pb2.GetMonitoringCycleRequest.FromString,
                    response_serializer=evaluations__pb2.GetMonitoringCycleResponse.SerializeToString,
            ),
            'GetWebpageComparisonData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWebpageComparisonData,
                    request_deserializer=evaluations__pb2.GetWebpageComparisonDataRequest.FromString,
                    response_serializer=evaluations__pb2.GetWebpageComparisonDataResponse.SerializeToString,
            ),
            'GetFailedTestsStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFailedTestsStats,
                    request_deserializer=evaluations__pb2.GetFailedTestsStatsRequest.FromString,
                    response_serializer=evaluations__pb2.GetFailedTestsStatsResponse.SerializeToString,
            ),
            'GetIntermediateCycles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntermediateCycles,
                    request_deserializer=evaluations__pb2.GetIntermediateCyclesRequest.FromString,
                    response_serializer=evaluations__pb2.GetIntermediateCyclesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runtimePackage.Evaluations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('runtimePackage.Evaluations', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Evaluations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddMonitoringRegistry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/AddMonitoringRegistry',
            evaluations__pb2.AddMonitoringRegistryRequest.SerializeToString,
            evaluations__pb2.AddMonitoringRegistryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddEvaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/AddEvaluation',
            evaluations__pb2.AddEvaluationRequest.SerializeToString,
            evaluations__pb2.AddEvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAccessibilityMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/SetAccessibilityMetric',
            evaluations__pb2.SetAccessibilityMetricRequest.SerializeToString,
            evaluations__pb2.SetAccessibilityMetricResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateAccessibilityScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/CalculateAccessibilityScore',
            evaluations__pb2.CalculateAccessibilityScoreRequest.SerializeToString,
            evaluations__pb2.CalculateAccessibilityScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLatestEvaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/SetLatestEvaluation',
            evaluations__pb2.SetLatestEvaluationRequest.SerializeToString,
            evaluations__pb2.SetLatestEvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddWebpages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/AddWebpages',
            evaluations__pb2.AddWebpagesRequest.SerializeToString,
            evaluations__pb2.AddWebpagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAccessibilityMetricAllWebsites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/SetAccessibilityMetricAllWebsites',
            evaluations__pb2.SetAccessibilityMetricAllWebsitesRequest.SerializeToString,
            evaluations__pb2.SetAccessibilityMetricAllWebsitesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentWarnings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetCurrentWarnings',
            evaluations__pb2.GetCurrentWarningsRequest.SerializeToString,
            evaluations__pb2.GetCurrentWarningsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWebsiteScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetWebsiteScore',
            evaluations__pb2.GetWebsiteScoreRequest.SerializeToString,
            evaluations__pb2.GetWebsiteScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIssuesStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetIssuesStats',
            evaluations__pb2.GetIssuesStatsRequest.SerializeToString,
            evaluations__pb2.GetIssuesStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWebpageScreenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetWebpageScreenshot',
            evaluations__pb2.GetWebpageScreenshotRequest.SerializeToString,
            evaluations__pb2.GetWebpageScreenshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestEvaluations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetLatestEvaluations',
            evaluations__pb2.GetLatestEvaluationsRequest.SerializeToString,
            evaluations__pb2.GetLatestEvaluationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestAssertions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetLatestAssertions',
            evaluations__pb2.GetLatestAssertionsRequest.SerializeToString,
            evaluations__pb2.GetLatestAssertionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssertionResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetAssertionResults',
            evaluations__pb2.GetAssertionResultsRequest.SerializeToString,
            evaluations__pb2.GetAssertionResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResultElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetResultElement',
            evaluations__pb2.GetResultElementsRequest.SerializeToString,
            evaluations__pb2.GetResultElementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvaluationHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetEvaluationHistory',
            evaluations__pb2.GetEvaluationHistoryRequest.SerializeToString,
            evaluations__pb2.GetEvaluationHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserMonitoringRegistries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetUserMonitoringRegistries',
            evaluations__pb2.GetUserMonitoringRegistriesRequest.SerializeToString,
            evaluations__pb2.GetUserMonitoringRegistriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWebsiteMonitoringCycles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetWebsiteMonitoringCycles',
            evaluations__pb2.GetWebsiteMonitoringCyclesRequest.SerializeToString,
            evaluations__pb2.GetWebsiteMonitoringCyclesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetNewMonitoringCycle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/SetNewMonitoringCycle',
            evaluations__pb2.SetNewMonitoringCycleRequest.SerializeToString,
            evaluations__pb2.SetNewMonitoringCycleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMonitoredWebpages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetMonitoredWebpages',
            evaluations__pb2.GetMonitoredWebpagesRequest.SerializeToString,
            evaluations__pb2.GetMonitoredWebpagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvaluationInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetEvaluationInfo',
            evaluations__pb2.GetEvaluationInfoRequest.SerializeToString,
            evaluations__pb2.GetEvaluationInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWebpage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/DeleteWebpage',
            evaluations__pb2.DeleteWebpageRequest.SerializeToString,
            evaluations__pb2.DeleteWebpageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddLatestEvaluationsToMonitoringCycle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/AddLatestEvaluationsToMonitoringCycle',
            evaluations__pb2.AddLatestEvaluationsToMonitoringCycleRequest.SerializeToString,
            evaluations__pb2.AddLatestEvaluationsToMonitoringCycleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMonitoringRegistry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetMonitoringRegistry',
            evaluations__pb2.GetMonitoringRegistryRequest.SerializeToString,
            evaluations__pb2.GetMonitoringRegistryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMonitoringCycle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetMonitoringCycle',
            evaluations__pb2.GetMonitoringCycleRequest.SerializeToString,
            evaluations__pb2.GetMonitoringCycleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWebpageComparisonData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetWebpageComparisonData',
            evaluations__pb2.GetWebpageComparisonDataRequest.SerializeToString,
            evaluations__pb2.GetWebpageComparisonDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFailedTestsStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetFailedTestsStats',
            evaluations__pb2.GetFailedTestsStatsRequest.SerializeToString,
            evaluations__pb2.GetFailedTestsStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIntermediateCycles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetIntermediateCycles',
            evaluations__pb2.GetIntermediateCyclesRequest.SerializeToString,
            evaluations__pb2.GetIntermediateCyclesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
