# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import evaluations_pb2 as evaluations__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in evaluations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EvaluationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddMonitoringRegistry = channel.unary_unary(
                '/runtimePackage.Evaluations/AddMonitoringRegistry',
                request_serializer=evaluations__pb2.AddMonitoringRegistryRequest.SerializeToString,
                response_deserializer=evaluations__pb2.AddMonitoringRegistryResponse.FromString,
                _registered_method=True)
        self.AddEvaluation = channel.unary_unary(
                '/runtimePackage.Evaluations/AddEvaluation',
                request_serializer=evaluations__pb2.AddEvaluationRequest.SerializeToString,
                response_deserializer=evaluations__pb2.AddEvaluationResponse.FromString,
                _registered_method=True)
        self.GetMonitoringRegistry = channel.unary_unary(
                '/runtimePackage.Evaluations/GetMonitoringRegistry',
                request_serializer=evaluations__pb2.GetMonitoringRegistryRequest.SerializeToString,
                response_deserializer=evaluations__pb2.GetMonitoringRegistryResponse.FromString,
                _registered_method=True)
        self.SetAccessibilityMetric = channel.unary_unary(
                '/runtimePackage.Evaluations/SetAccessibilityMetric',
                request_serializer=evaluations__pb2.SetAccessibilityMetricRequest.SerializeToString,
                response_deserializer=evaluations__pb2.SetAccessibilityMetricResponse.FromString,
                _registered_method=True)
        self.CalculateAccessibilityScore = channel.unary_unary(
                '/runtimePackage.Evaluations/CalculateAccessibilityScore',
                request_serializer=evaluations__pb2.CalculateAccessibilityScoreRequest.SerializeToString,
                response_deserializer=evaluations__pb2.CalculateAccessibilityScoreResponse.FromString,
                _registered_method=True)
        self.SetLatestEvaluation = channel.unary_unary(
                '/runtimePackage.Evaluations/SetLatestEvaluation',
                request_serializer=evaluations__pb2.SetLatestEvaluationRequest.SerializeToString,
                response_deserializer=evaluations__pb2.SetLatestEvaluationResponse.FromString,
                _registered_method=True)
        self.AddWebpages = channel.unary_unary(
                '/runtimePackage.Evaluations/AddWebpages',
                request_serializer=evaluations__pb2.AddWebpagesRequest.SerializeToString,
                response_deserializer=evaluations__pb2.AddWebpagesResponse.FromString,
                _registered_method=True)
        self.SetAccessibilityMetricAllWebsites = channel.unary_unary(
                '/runtimePackage.Evaluations/SetAccessibilityMetricAllWebsites',
                request_serializer=evaluations__pb2.SetAccessibilityMetricAllWebsitesRequest.SerializeToString,
                response_deserializer=evaluations__pb2.SetAccessibilityMetricAllWebsitesResponse.FromString,
                _registered_method=True)


class EvaluationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddMonitoringRegistry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddEvaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMonitoringRegistry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAccessibilityMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateAccessibilityScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLatestEvaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddWebpages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAccessibilityMetricAllWebsites(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EvaluationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddMonitoringRegistry': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMonitoringRegistry,
                    request_deserializer=evaluations__pb2.AddMonitoringRegistryRequest.FromString,
                    response_serializer=evaluations__pb2.AddMonitoringRegistryResponse.SerializeToString,
            ),
            'AddEvaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEvaluation,
                    request_deserializer=evaluations__pb2.AddEvaluationRequest.FromString,
                    response_serializer=evaluations__pb2.AddEvaluationResponse.SerializeToString,
            ),
            'GetMonitoringRegistry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMonitoringRegistry,
                    request_deserializer=evaluations__pb2.GetMonitoringRegistryRequest.FromString,
                    response_serializer=evaluations__pb2.GetMonitoringRegistryResponse.SerializeToString,
            ),
            'SetAccessibilityMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAccessibilityMetric,
                    request_deserializer=evaluations__pb2.SetAccessibilityMetricRequest.FromString,
                    response_serializer=evaluations__pb2.SetAccessibilityMetricResponse.SerializeToString,
            ),
            'CalculateAccessibilityScore': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateAccessibilityScore,
                    request_deserializer=evaluations__pb2.CalculateAccessibilityScoreRequest.FromString,
                    response_serializer=evaluations__pb2.CalculateAccessibilityScoreResponse.SerializeToString,
            ),
            'SetLatestEvaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLatestEvaluation,
                    request_deserializer=evaluations__pb2.SetLatestEvaluationRequest.FromString,
                    response_serializer=evaluations__pb2.SetLatestEvaluationResponse.SerializeToString,
            ),
            'AddWebpages': grpc.unary_unary_rpc_method_handler(
                    servicer.AddWebpages,
                    request_deserializer=evaluations__pb2.AddWebpagesRequest.FromString,
                    response_serializer=evaluations__pb2.AddWebpagesResponse.SerializeToString,
            ),
            'SetAccessibilityMetricAllWebsites': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAccessibilityMetricAllWebsites,
                    request_deserializer=evaluations__pb2.SetAccessibilityMetricAllWebsitesRequest.FromString,
                    response_serializer=evaluations__pb2.SetAccessibilityMetricAllWebsitesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runtimePackage.Evaluations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('runtimePackage.Evaluations', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Evaluations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddMonitoringRegistry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/AddMonitoringRegistry',
            evaluations__pb2.AddMonitoringRegistryRequest.SerializeToString,
            evaluations__pb2.AddMonitoringRegistryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddEvaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/AddEvaluation',
            evaluations__pb2.AddEvaluationRequest.SerializeToString,
            evaluations__pb2.AddEvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMonitoringRegistry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/GetMonitoringRegistry',
            evaluations__pb2.GetMonitoringRegistryRequest.SerializeToString,
            evaluations__pb2.GetMonitoringRegistryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAccessibilityMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/SetAccessibilityMetric',
            evaluations__pb2.SetAccessibilityMetricRequest.SerializeToString,
            evaluations__pb2.SetAccessibilityMetricResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateAccessibilityScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/CalculateAccessibilityScore',
            evaluations__pb2.CalculateAccessibilityScoreRequest.SerializeToString,
            evaluations__pb2.CalculateAccessibilityScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLatestEvaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/SetLatestEvaluation',
            evaluations__pb2.SetLatestEvaluationRequest.SerializeToString,
            evaluations__pb2.SetLatestEvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddWebpages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/AddWebpages',
            evaluations__pb2.AddWebpagesRequest.SerializeToString,
            evaluations__pb2.AddWebpagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAccessibilityMetricAllWebsites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtimePackage.Evaluations/SetAccessibilityMetricAllWebsites',
            evaluations__pb2.SetAccessibilityMetricAllWebsitesRequest.SerializeToString,
            evaluations__pb2.SetAccessibilityMetricAllWebsitesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
