# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: issues.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'issues.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cissues.proto\x12\x0eruntimePackage\"2\n\x0cIssueElement\x12\x11\n\thtml_code\x18\x01 \x01(\t\x12\x0f\n\x07pointer\x18\x02 \x01(\t\"\xa3\x01\n\x05Issue\x12\x14\n\x0c\x61ssertion_id\x18\x01 \x01(\x05\x12\x0f\n\x07verdict\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0bresult_code\x18\x04 \x01(\t\x12.\n\x08\x65lements\x18\x05 \x03(\x0b\x32\x1c.runtimePackage.IssueElement\x12\x19\n\x11\x65lements_quantity\x18\x06 \x01(\x05\"R\n\x10\x41\x64\x64IssuesRequest\x12%\n\x06issues\x18\x01 \x03(\x0b\x32\x15.runtimePackage.Issue\x12\x17\n\x0fissues_quantity\x18\x02 \x01(\x05\"(\n\x11\x41\x64\x64IssuesResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x32Z\n\x06Issues\x12P\n\tAddIssues\x12 .runtimePackage.AddIssuesRequest\x1a!.runtimePackage.AddIssuesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'issues_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ISSUEELEMENT']._serialized_start=32
  _globals['_ISSUEELEMENT']._serialized_end=82
  _globals['_ISSUE']._serialized_start=85
  _globals['_ISSUE']._serialized_end=248
  _globals['_ADDISSUESREQUEST']._serialized_start=250
  _globals['_ADDISSUESREQUEST']._serialized_end=332
  _globals['_ADDISSUESRESPONSE']._serialized_start=334
  _globals['_ADDISSUESRESPONSE']._serialized_end=374
  _globals['_ISSUES']._serialized_start=376
  _globals['_ISSUES']._serialized_end=466
# @@protoc_insertion_point(module_scope)
